version: '3.9'

services:
  redmine:
    image: redmine:passenger
    container_name: redmine

    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_ENCODING: utf8
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./docker/redmine/files:/usr/src/redmine/files
      - ./docker/redmine/log:/usr/src/redmine/log
      - ./docker/redmine/plugins:/usr/src/redmine/plugins
      - ./docker/redmine/public/themes:/usr/src/redmine/public/themes

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/content:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/gitlab/config:/etc/gitlab
      - ./docker/gitlab/logs:/var/log/gitlab
      - ./docker/gitlab/data:/var/opt/gitlab

  # jira:
  #   image: atlassian/jira-software:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./jira_data:/var/atlassian/jira

