// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BocchiTracker.ProcessLinkQuery.Queries
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct IssueesRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static IssueesRequest GetRootAsIssueesRequest(ByteBuffer _bb) { return GetRootAsIssueesRequest(_bb, new IssueesRequest()); }
  public static IssueesRequest GetRootAsIssueesRequest(ByteBuffer _bb, IssueesRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public IssueesRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public BocchiTracker.ProcessLinkQuery.Queries.Issue? Issues(int j) { int o = __p.__offset(4); return o != 0 ? (BocchiTracker.ProcessLinkQuery.Queries.Issue?)(new BocchiTracker.ProcessLinkQuery.Queries.Issue()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int IssuesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.IssueesRequest> CreateIssueesRequest(FlatBufferBuilder builder,
      VectorOffset issuesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    IssueesRequest.AddIssues(builder, issuesOffset);
    return IssueesRequest.EndIssueesRequest(builder);
  }

  public static void StartIssueesRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddIssues(FlatBufferBuilder builder, VectorOffset issuesOffset) { builder.AddOffset(0, issuesOffset.Value, 0); }
  public static VectorOffset CreateIssuesVector(FlatBufferBuilder builder, Offset<BocchiTracker.ProcessLinkQuery.Queries.Issue>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateIssuesVectorBlock(FlatBufferBuilder builder, Offset<BocchiTracker.ProcessLinkQuery.Queries.Issue>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIssuesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BocchiTracker.ProcessLinkQuery.Queries.Issue>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIssuesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BocchiTracker.ProcessLinkQuery.Queries.Issue>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartIssuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.IssueesRequest> EndIssueesRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BocchiTracker.ProcessLinkQuery.Queries.IssueesRequest>(o);
  }
}


static public class IssueesRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Issues*/, BocchiTracker.ProcessLinkQuery.Queries.IssueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
