// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BocchiTracker.ProcessLinkQuery.Queries
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JumpRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static JumpRequest GetRootAsJumpRequest(ByteBuffer _bb) { return GetRootAsJumpRequest(_bb, new JumpRequest()); }
  public static JumpRequest GetRootAsJumpRequest(ByteBuffer _bb, JumpRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JumpRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public BocchiTracker.ProcessLinkQuery.Queries.Vec3? Location { get { int o = __p.__offset(4); return o != 0 ? (BocchiTracker.ProcessLinkQuery.Queries.Vec3?)(new BocchiTracker.ProcessLinkQuery.Queries.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public string Stage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetStageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetStageArray() { return __p.__vector_as_array<byte>(6); }

  public static void StartJumpRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLocation(FlatBufferBuilder builder, Offset<BocchiTracker.ProcessLinkQuery.Queries.Vec3> locationOffset) { builder.AddStruct(0, locationOffset.Value, 0); }
  public static void AddStage(FlatBufferBuilder builder, StringOffset stageOffset) { builder.AddOffset(1, stageOffset.Value, 0); }
  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.JumpRequest> EndJumpRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BocchiTracker.ProcessLinkQuery.Queries.JumpRequest>(o);
  }
}


static public class JumpRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Location*/, 12 /*BocchiTracker.ProcessLinkQuery.Queries.Vec3*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Stage*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
