// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BocchiTracker.ProcessLinkQuery.Queries
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ScreenshotRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ScreenshotRequest GetRootAsScreenshotRequest(ByteBuffer _bb) { return GetRootAsScreenshotRequest(_bb, new ScreenshotRequest()); }
  public static ScreenshotRequest GetRootAsScreenshotRequest(ByteBuffer _bb, ScreenshotRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ScreenshotRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartScreenshotRequest(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.ScreenshotRequest> EndScreenshotRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BocchiTracker.ProcessLinkQuery.Queries.ScreenshotRequest>(o);
  }
}


static public class ScreenshotRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
