// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BocchiTracker.ProcessLinkQuery.Queries
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LogData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static LogData GetRootAsLogData(ByteBuffer _bb) { return GetRootAsLogData(_bb, new LogData()); }
  public static LogData GetRootAsLogData(ByteBuffer _bb, LogData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LogData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Log(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int LogLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.LogData> CreateLogData(FlatBufferBuilder builder,
      VectorOffset logOffset = default(VectorOffset)) {
    builder.StartTable(1);
    LogData.AddLog(builder, logOffset);
    return LogData.EndLogData(builder);
  }

  public static void StartLogData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLog(FlatBufferBuilder builder, VectorOffset logOffset) { builder.AddOffset(0, logOffset.Value, 0); }
  public static VectorOffset CreateLogVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLogVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLogVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLogVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLogVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.LogData> EndLogData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BocchiTracker.ProcessLinkQuery.Queries.LogData>(o);
  }
}


static public class LogDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfStrings(tablePos, 4 /*Log*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
