// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BocchiTracker.ProcessLinkQuery.Queries
{

public enum QueryID : byte
{
  NONE = 0,
  AppBasicInfo = 1,
  RequestQuery = 2,
  PlayerPosition = 3,
  ScreenshotData = 4,
};


}
