// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BocchiTracker.ProcessLinkQuery.Queries
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AppBasicInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static AppBasicInfo GetRootAsAppBasicInfo(ByteBuffer _bb) { return GetRootAsAppBasicInfo(_bb, new AppBasicInfo()); }
  public static AppBasicInfo GetRootAsAppBasicInfo(ByteBuffer _bb, AppBasicInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AppBasicInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Pid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string AppName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAppNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetAppNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetAppNameArray() { return __p.__vector_as_array<byte>(6); }
  public string Args { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetArgsBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetArgsBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetArgsArray() { return __p.__vector_as_array<byte>(8); }
  public string Platform { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlatformBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetPlatformBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetPlatformArray() { return __p.__vector_as_array<byte>(10); }
  public string LogFilepath { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLogFilepathBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetLogFilepathBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetLogFilepathArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.AppBasicInfo> CreateAppBasicInfo(FlatBufferBuilder builder,
      int pid = 0,
      StringOffset app_nameOffset = default(StringOffset),
      StringOffset argsOffset = default(StringOffset),
      StringOffset platformOffset = default(StringOffset),
      StringOffset log_filepathOffset = default(StringOffset)) {
    builder.StartTable(5);
    AppBasicInfo.AddLogFilepath(builder, log_filepathOffset);
    AppBasicInfo.AddPlatform(builder, platformOffset);
    AppBasicInfo.AddArgs(builder, argsOffset);
    AppBasicInfo.AddAppName(builder, app_nameOffset);
    AppBasicInfo.AddPid(builder, pid);
    return AppBasicInfo.EndAppBasicInfo(builder);
  }

  public static void StartAppBasicInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddPid(FlatBufferBuilder builder, int pid) { builder.AddInt(0, pid, 0); }
  public static void AddAppName(FlatBufferBuilder builder, StringOffset appNameOffset) { builder.AddOffset(1, appNameOffset.Value, 0); }
  public static void AddArgs(FlatBufferBuilder builder, StringOffset argsOffset) { builder.AddOffset(2, argsOffset.Value, 0); }
  public static void AddPlatform(FlatBufferBuilder builder, StringOffset platformOffset) { builder.AddOffset(3, platformOffset.Value, 0); }
  public static void AddLogFilepath(FlatBufferBuilder builder, StringOffset logFilepathOffset) { builder.AddOffset(4, logFilepathOffset.Value, 0); }
  public static Offset<BocchiTracker.ProcessLinkQuery.Queries.AppBasicInfo> EndAppBasicInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BocchiTracker.ProcessLinkQuery.Queries.AppBasicInfo>(o);
  }
}


static public class AppBasicInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Pid*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*AppName*/, false)
      && verifier.VerifyString(tablePos, 8 /*Args*/, false)
      && verifier.VerifyString(tablePos, 10 /*Platform*/, false)
      && verifier.VerifyString(tablePos, 12 /*LogFilepath*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
