// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BocchiTracker.ProcessLinkQuery.Queries
{

public enum QueryID : byte
{
  NONE = 0,
  AppBasicInfo = 1,
  PlayerPosition = 2,
  ScreenshotData = 3,
  LogData = 4,
  ScreenshotRequest = 5,
  JumpRequest = 6,
  IssueesRequest = 7,
};


}
