name: Codecov

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore Application/BocchiTracker.UnitTests.sln

    - name: Build unit Test 
      run: dotnet build --no-restore Application/BocchiTracker.UnitTests.sln

    - name: Execute unit test
      run: dotnet test --no-build --verbosity normal Application/BocchiTracker.UnitTests.sln

    - name: upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
