name: Build and unit tests
permissions: read-all

on: 
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      Builder: 1
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Application/BocchiTracker.UnitTests.sln
    - name: Build
      run: dotnet build --no-restore Application/BocchiTracker.UnitTests.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Application/BocchiTracker.UnitTests.sln

  build-windows:
    runs-on: windows-latest
    env:
      Builder: 2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET on Windows
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
    - name: Build Application Debug
      run: dotnet restore Application/BocchiTracker.UnitTests.sln -c Debug
    - name: Build Application Release
      run: dotnet build Application/BocchiTracker.WPF.sln -c Release
    - name: Build
      run: dotnet build --no-restore Application/BocchiTracker.UnitTests.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Application/BocchiTracker.UnitTests.sln
